"""add macros and via to calorie_logs

Revision ID: 765fec47613b
Revises: ae772f6fbce6
Create Date: 2026-06-03 15:52:40.294683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '765fec47613b'
down_revision: Union[str, Sequence[str], None] = 'ae772f6fbce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calorie_logs', sa.Column('protein_g', sa.Float(), nullable=True))
    op.add_column('calorie_logs', sa.Column('carbs_g', sa.Float(), nullable=True))
    op.add_column('calorie_logs', sa.Column('fat_g', sa.Float(), nullable=True))
    op.add_column('calorie_logs', sa.Column('via', sa.String(length=20), server_default='manual', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calorie_logs', 'via')
    op.drop_column('calorie_logs', 'fat_g')
    op.drop_column('calorie_logs', 'carbs_g')
    op.drop_column('calorie_logs', 'protein_g')
    # ### end Alembic commands ###
