"""add daily_calorie_goal to users

Revision ID: ae772f6fbce6
Revises: 4b83944a7a60
Create Date: 2026-06-03 11:02:12.539219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae772f6fbce6'
down_revision: Union[str, Sequence[str], None] = '4b83944a7a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_calorie_goal', sa.Integer(), server_default='2000', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_calorie_goal')
    # ### end Alembic commands ###
